version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - backend
    command: sh -c "yarn && yarn dev"
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend.Dockerfile
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./apps/backend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev
