export const practitioners = [
    {
        id: "najoomi-1",
        name: "Mufti Abdul Raheem",
        title: "Islamic Scholar & Spiritual Guide",
        image: "/missions.png",
        experience: "15+ years",
        specialties: ["Dream Interpretation", "Istikhara", "Spiritual Counseling"],
        rating: 5,
        price: "599",
        discountPrice: "299",
        starPractitioner: true,
        type: "najoomi",
        duration: "15 minutes",
        description: "Book a 1:1 session with Mufti Abdul Raheem for dream interpretation, istikhara, and spiritual guidance rooted in Islamic wisdom. Experience clarity and peace through authentic spiritual counsel."

    },
    {
        id: "najoomi-2",
        name: "Shaykha Amina Hassan",
        duration: "15 minutes",
        description: "Connect with Shaykha Amina Hassan for ruqyah, spiritual cleansing, and family counseling. Receive compassionate guidance and protection through Quranic healing and Islamic tradition.",
        title: "Ruqyah Specialist & Counselor",
        image: "/missions.png",
        experience: "12+ years",
        specialties: ["Ruqyah", "Spiritual Cleansing", "Family Counseling"],
        rating: 5,
        price: "1000",
        discountPrice: "800",
        type: "najoomi"
    },
    {
        id: "najoomi-3",
        name: "Ustadh Ibrahim Malik",
        duration: "15 minutes",
        description: "Book a session with Ustadh Ibrahim Malik for ilm-e-adad (Islamic numerology), rohani healing, and meaningful baby naming. Discover spiritual insights and solutions tailored to your unique journey.",
        title: "Numerologist & Spiritual Healer",
        image: "/missions.png",
        experience: "20+ years",
        specialties: ["Ilm-e-Adad", "Rohani Healing", "Baby Naming"],
        rating: 5,
        price: "1000",
        discountPrice: "800",
        type: "najoomi"
    },
    {
        id: "therapist-1",
        name: "Dr. Sara Qureshi",
        duration: "45 minutes",
        description: "Consult with Dr. Sara Qureshi, a clinical psychologist blending modern therapy with Islamic values. Address anxiety, depression, and emotional challenges in a safe, faith-centered environment.",
        title: "Clinical Psychologist",
        image: "/missions.png",
        experience: "8+ years",
        specialties: ["CBT", "Anxiety", "Depression"],
        rating: 5,
        price: "1500",
        discountPrice: "1200",
        type: "therapist",
        starPractitioner: true,
    },
    {
        id: "therapist-2",
        name: "Adeel Khan",
        title: "Licensed Therapist",
        image: "/missions.png",
        experience: "10+ years",
        specialties: ["Relationship Counseling", "Stress Management", "Mindfulness"],
        rating: 5,
        price: "1200",
        discountPrice: "950",
        type: "therapist",
        duration: "45 minutes",
        description: "Book with Adeel Khan for relationship counseling, stress management, and mindfulness. Benefit from licensed therapy that honors your emotional and spiritual well-being."
    },
    {
        id: "therapist-3",
        name: "Fatima Siddiqui",
        duration: "45 minutes",
        description: "Connect with Fatima Siddiqui, specialist in child and adolescent therapy. Support your family with expert guidance on behavioral issues and holistic, faith-inspired care.",
        title: "Child & Adolescent Therapist",
        image: "/missions.png",
        experience: "6+ years",
        specialties: ["Child Therapy", "Family Therapy", "Behavioral Issues"],
        rating: 5,
        price: "1300",
        discountPrice: "1100",
        type: "therapist"
    },

];